import { rename, writeFile } from "node:fs/promises";
import path from "node:path";

type Override = {
  styles: Record<string, string>;
  text?: string;
};

type OverrideFile = {
  version: 1;
  overrides: Record<string, Override>;
};

const allowedProperties = new Set([
  "width",
  "height",
  "padding",
  "margin",
  "gap",
  "color",
  "backgroundColor",
  "fontSize",
  "fontWeight",
  "borderRadius",
  "backgroundPosition",
  "objectPosition",
]);

function cssName(property: string) {
  return property.replace(/[A-Z]/g, (letter) => `-${letter.toLowerCase()}`);
}

function validate(input: unknown): OverrideFile {
  if (!input || typeof input !== "object") throw new Error("Invalid payload");
  const file = input as Partial<OverrideFile>;
  if (file.version !== 1 || !file.overrides || typeof file.overrides !== "object") {
    throw new Error("Invalid override format");
  }
  if (Object.keys(file.overrides).length > 250) throw new Error("Too many overrides");

  for (const [selector, override] of Object.entries(file.overrides)) {
    if (!selector || selector.length > 1000 || !override || typeof override !== "object") {
      throw new Error("Invalid selector or override");
    }
    if (override.text !== undefined && (typeof override.text !== "string" || override.text.length > 5000)) {
      throw new Error("Invalid text value");
    }
    for (const [property, value] of Object.entries(override.styles ?? {})) {
      if (!allowedProperties.has(property) || typeof value !== "string" || value.length > 300) {
        throw new Error(`Unsupported style: ${property}`);
      }
      if (/url\s*\(|expression\s*\(|javascript:/i.test(value)) {
        throw new Error("Unsafe CSS value");
      }
    }
  }
  return file as OverrideFile;
}

function toCss(file: OverrideFile) {
  return [
    "/* Generated by Visual UI Editor. Review and commit intentionally. */",
    ...Object.entries(file.overrides).map(([selector, override]) => {
      const declarations = Object.entries(override.styles)
        .map(([property, value]) => `  ${cssName(property)}: ${value} !important;`)
        .join("\n");
      return declarations ? `${selector} {\n${declarations}\n}` : "";
    }),
    "",
  ].join("\n");
}

async function atomicWrite(filePath: string, content: string) {
  const temporaryPath = `${filePath}.tmp`;
  await writeFile(temporaryPath, content, "utf8");
  await rename(temporaryPath, filePath);
}

export async function POST(request: Request) {
  if (process.env.NODE_ENV !== "development") {
    return Response.json({ error: "Visual editor is development-only" }, { status: 404 });
  }

  try {
    const raw = await request.text();
    if (raw.length > 1_000_000) {
      return Response.json({ error: "Payload too large" }, { status: 413 });
    }
    const file = validate(JSON.parse(raw));
    const appDirectory = path.join(process.cwd(), "src", "app");
    await atomicWrite(
      path.join(appDirectory, "visual-editor.generated.json"),
      `${JSON.stringify(file, null, 2)}\n`,
    );
    await atomicWrite(path.join(appDirectory, "visual-editor.generated.css"), toCss(file));
    return Response.json({ ok: true });
  } catch (error) {
    const message = error instanceof Error ? error.message : "Unable to save";
    return Response.json({ error: message }, { status: 400 });
  }
}

