export const ICON_CATEGORIES = [
  "Popular",
  "Work & Business",
  "Productivity",
  "Design",
  "Development",
  "AI & Automation",
  "Data & Analytics",
  "Communication",
  "Files & Documents",
  "Media",
  "Education",
  "Finance & Commerce",
  "Security",
  "Cloud & Network",
  "Devices & Hardware",
  "Travel & Location",
  "Health & Lifestyle",
  "Nature & Weather",
  "Buildings & Places",
  "Actions & Status"
] as const;

export type ToolIconCategory = (typeof ICON_CATEGORIES)[number];

export interface ToolIconMetadata {
  key: string;
  label: string;
  category: ToolIconCategory;
  keywords: readonly string[];
  lucideName?: string;
}

const ICON_KEYS_BY_CATEGORY = {
  "Popular": [
    "app-window",
    "home",
    "search",
    "settings",
    "star",
    "heart",
    "bookmark",
    "user",
    "users",
    "bell",
    "calendar-days",
    "clock",
    "check-circle",
    "circle-plus",
    "external-link",
    "link",
    "app-window-mac",
    "bell-check",
    "bell-electric",
    "bell-minus",
    "bell-plus",
    "bell-ring",
    "bookmark-check",
    "bookmark-minus",
    "bookmark-plus",
  ],
  "Work & Business": [
    "briefcase-business",
    "building",
    "presentation",
    "bar-chart",
    "pie-chart",
    "trending-up",
    "target",
    "clipboard-list",
    "list-todo",
    "kanban",
    "mail",
    "phone",
    "contact",
    "badge-check",
    "area-chart",
    "badge",
    "badge-alert",
    "badge-cent",
    "badge-dollar-sign",
    "badge-euro",
    "badge-help",
    "badge-indian-rupee",
    "badge-info",
    "badge-japanese-yen",
    "badge-minus",
  ],
  "Productivity": [
    "lightbulb",
    "alarm-check",
    "alarm-clock",
    "alarm-clock-check",
    "alarm-clock-minus",
    "alarm-clock-plus",
    "alarm-minus",
    "alarm-plus",
    "alarm-smoke",
    "archive",
    "archive-restore",
    "archive-x",
    "banknote-check",
    "book-check",
    "book-open-check",
    "calendar",
    "calendar-1",
    "calendar-arrow-down",
    "calendar-arrow-up",
    "calendar-check",
    "calendar-check-2",
    "calendar-clock",
    "calendar-cog",
    "calendar-fold",
    "calendar-heart",
  ],
  "Design": [
    "palette",
    "brush",
    "pen-tool",
    "pencil",
    "shapes",
    "layers",
    "image",
    "camera",
    "magic-wand",
    "sparkles",
    "frame",
    "crop",
    "pipette",
    "swatch-book",
    "blend",
    "blender",
    "book-image",
    "book-open",
    "book-open-text",
    "brush-cleaning",
    "clipboard-pen",
    "clipboard-pen-line",
    "component",
    "contrast",
    "door-open",
  ],
  "Development": [
    "code",
    "terminal",
    "braces",
    "file-code",
    "bug",
    "git-branch",
    "git-pull-request",
    "database",
    "server",
    "cloud",
    "cpu",
    "bot",
    "workflow",
    "webhook",
    "barcode",
    "binary",
    "brackets",
    "bug-play",
    "code-2",
    "code-square",
    "code-xml",
    "command",
    "container",
    "curly-braces",
    "database-arrow-down",
  ],
  "AI & Automation": [
    "atom",
    "audio-waveform",
    "badge-percent",
    "badge-plus",
    "badge-pound-sterling",
    "badge-question-mark",
    "badge-russian-ruble",
    "badge-swiss-franc",
    "badge-turkish-lira",
    "badge-x",
    "bot-message-square",
    "bottle-wine",
    "brain",
    "brain-circuit",
    "brain-cog",
    "chart-network",
    "circuit-board",
    "cloud-cog",
    "cog",
    "columns-3-cog",
    "file-badge",
    "file-badge-2",
    "file-cog",
    "file-cog-2",
    "file-scan",
  ],
  "Data & Analytics": [
    "activity",
    "activity-square",
    "arrows-up-from-line",
    "bar-chart-2",
    "bar-chart-3",
    "bar-chart-4",
    "bar-chart-big",
    "bar-chart-horizontal",
    "bar-chart-horizontal-big",
    "baseline",
    "calculator",
    "candlestick-chart",
    "chart-area",
    "chart-bar",
    "chart-bar-big",
    "chart-bar-decreasing",
    "chart-bar-increasing",
    "chart-bar-stacked",
    "chart-candlestick",
    "chart-column",
    "chart-column-big",
    "chart-column-decreasing",
    "chart-column-increasing",
    "chart-column-stacked",
    "chart-gantt",
  ],
  "Communication": [
    "at-sign",
    "book-headphones",
    "concierge-bell",
    "contact-2",
    "contact-round",
    "dumbbell",
    "file-headphone",
    "file-video-2",
    "file-video-camera",
    "inbox",
    "languages",
    "list-video",
    "mail-check",
    "mail-minus",
    "mail-open",
    "mail-plus",
    "mail-question",
    "mail-question-mark",
    "mail-search",
    "mail-warning",
    "mail-x",
    "mailbox",
    "mails",
    "megaphone",
    "message-circle",
  ],
  "Files & Documents": [
    "file",
    "files",
    "folder",
    "folder-open",
    "file-text",
    "file-spreadsheet",
    "file-image",
    "file-video",
    "file-audio",
    "file-archive",
    "download",
    "upload",
    "save",
    "paperclip",
    "clipboard",
    "clipboard-check",
    "clipboard-clock",
    "clipboard-copy",
    "clipboard-edit",
    "clipboard-minus",
    "clipboard-paste",
    "clipboard-plus",
    "clipboard-signature",
    "clipboard-type",
    "clipboard-x",
  ],
  "Media": [
    "play",
    "pause",
    "music",
    "video",
    "mic",
    "headphones",
    "volume",
    "radio",
    "podcast",
    "film",
    "clapperboard",
    "disc",
    "audio-lines",
    "gallery",
    "airplay",
    "book-audio",
    "disc-2",
    "disc-3",
    "disc-album",
    "fast-forward",
    "file-audio-2",
    "file-music",
    "file-play",
    "file-volume",
    "file-volume-2",
  ],
  "Education": [
    "award",
    "book",
    "book-a",
    "book-alert",
    "book-copy",
    "book-down",
    "book-heart",
    "book-key",
    "book-lock",
    "book-marked",
    "book-minus",
    "book-plus",
    "book-search",
    "book-template",
    "book-text",
    "book-type",
    "book-up",
    "book-up-2",
    "book-user",
    "book-x",
    "bookmark-x",
    "flask-conical",
    "flask-round",
    "folder-bookmark",
    "graduation-cap",
  ],
  "Finance & Commerce": [
    "package",
    "shopping-cart",
    "gift",
    "banknote",
    "banknote-arrow-down",
    "banknote-arrow-up",
    "banknote-x",
    "coins",
    "credit-card",
    "diamond-percent",
    "dollar-sign",
    "euro",
    "hand-coins",
    "japanese-yen",
    "landmark",
    "package-2",
    "package-check",
    "package-minus",
    "package-open",
    "package-plus",
    "package-search",
    "package-x",
    "percent",
    "percent-circle",
    "percent-diamond",
  ],
  "Security": [
    "key",
    "lock",
    "shield-check",
    "blocks",
    "brick-wall-shield",
    "clock-1",
    "clock-10",
    "clock-11",
    "clock-12",
    "clock-2",
    "clock-3",
    "clock-4",
    "clock-5",
    "clock-6",
    "clock-7",
    "clock-8",
    "clock-9",
    "clock-alert",
    "clock-arrow-down",
    "clock-arrow-left",
    "clock-arrow-right",
    "clock-arrow-up",
    "clock-check",
    "clock-fading",
    "clock-plus",
  ],
  "Cloud & Network": [
    "globe",
    "antenna",
    "cable",
    "cable-car",
    "cloud-alert",
    "cloud-backup",
    "cloud-check",
    "cloud-download",
    "cloud-drizzle",
    "cloud-fog",
    "cloud-hail",
    "cloud-lightning",
    "cloud-moon",
    "cloud-moon-rain",
    "cloud-rain",
    "cloud-rain-wind",
    "cloud-snow",
    "cloud-sun",
    "cloud-sun-rain",
    "cloud-sync",
    "cloud-upload",
    "cloudy",
    "database-arrow-up",
    "database-backup",
    "database-check",
  ],
  "Devices & Hardware": [
    "wrench",
    "hammer",
    "battery",
    "battery-charging",
    "battery-full",
    "battery-low",
    "battery-medium",
    "battery-plus",
    "battery-warning",
    "hard-drive",
    "hard-drive-download",
    "hard-drive-upload",
    "house-plug",
    "keyboard",
    "keyboard-music",
    "laptop",
    "laptop-2",
    "laptop-minimal",
    "laptop-minimal-check",
    "memory-stick",
    "monitor",
    "monitor-check",
    "monitor-cloud",
    "monitor-cog",
    "monitor-down",
  ],
  "Travel & Location": [
    "map",
    "map-pin",
    "compass",
    "bike",
    "bus",
    "bus-front",
    "car",
    "car-front",
    "car-taxi-front",
    "caravan",
    "card-sim",
    "carrot",
    "drafting-compass",
    "hand-helping",
    "helping-hand",
    "hotel",
    "id-card",
    "id-card-lanyard",
    "loader-pinwheel",
    "luggage",
    "map-minus",
    "map-pin-check",
    "map-pin-check-inside",
    "map-pin-house",
    "map-pin-minus",
  ],
  "Health & Lifestyle": [
    "accessibility",
    "apple",
    "baby",
    "bath",
    "bed",
    "bed-double",
    "bed-single",
    "coffee",
    "file-heart",
    "folder-heart",
    "footprints",
    "hand-heart",
    "heart-crack",
    "heart-handshake",
    "heart-minus",
    "heart-plus",
    "heart-pulse",
    "heart-x",
    "hospital",
    "house-heart",
    "message-circle-heart",
    "message-square-heart",
    "person-standing",
    "pill",
    "pill-bottle",
  ],
  "Nature & Weather": [
    "download-cloud",
    "droplet",
    "droplets",
    "flame",
    "flame-kindling",
    "flower",
    "flower-2",
    "folder-tree",
    "leaf",
    "leafy-green",
    "list-tree",
    "moon",
    "moon-star",
    "mountain",
    "mountain-snow",
    "palmtree",
    "rainbow",
    "rewind",
    "snowflake",
    "soap-dispenser-droplet",
    "sprout",
    "sun",
    "sun-dim",
    "sun-medium",
    "sun-moon",
  ],
  "Buildings & Places": [
    "birdhouse",
    "building-2",
    "castle",
    "church",
    "factory",
    "house",
    "house-plus",
    "house-wifi",
    "library",
    "library-big",
    "library-square",
    "school",
    "school-2",
    "store",
    "table-of-contents",
    "tent",
    "tent-tree",
    "theater",
    "trees",
    "university",
    "warehouse",
    "a-large-small",
    "ad",
    "air-vent",
    "album",
  ],
  "Actions & Status": [
    "rocket",
    "a-arrow-down",
    "a-arrow-up",
    "alert-circle",
    "alert-triangle",
    "arrow-big-down",
    "arrow-big-down-dash",
    "arrow-big-left",
    "arrow-big-left-dash",
    "arrow-big-right",
    "arrow-big-right-dash",
    "arrow-big-up",
    "arrow-big-up-dash",
    "arrow-down",
    "arrow-down-0-1",
    "arrow-down-01",
    "arrow-down-1-0",
    "arrow-down-10",
    "arrow-down-a-z",
    "arrow-down-az",
    "arrow-down-circle",
    "arrow-down-from-line",
    "arrow-down-left",
    "arrow-down-left-from-circle",
    "arrow-down-left-from-square",
  ],
} as const satisfies Record<ToolIconCategory, readonly string[]>;

const CATEGORY_KEYWORDS = {
  "Popular": ["common","favorite","常用","热门"],
  "Work & Business": ["work","business","office","工作","商务"],
  "Productivity": ["productivity","task","plan","效率","任务"],
  "Design": ["design","creative","设计","创意"],
  "Development": ["development","code","developer","开发","代码"],
  "AI & Automation": ["ai","automation","agent","人工智能","自动化"],
  "Data & Analytics": ["data","analytics","report","数据","分析"],
  "Communication": ["communication","message","contact","沟通","消息"],
  "Files & Documents": ["file","document","folder","文件","文档"],
  "Media": ["media","audio","video","媒体","影音"],
  "Education": ["education","learning","study","教育","学习"],
  "Finance & Commerce": ["finance","commerce","money","财务","商业"],
  "Security": ["security","privacy","安全","隐私"],
  "Cloud & Network": ["cloud","network","internet","云","网络"],
  "Devices & Hardware": ["device","hardware","设备","硬件"],
  "Travel & Location": ["travel","location","map","旅行","位置"],
  "Health & Lifestyle": ["health","lifestyle","健康","生活"],
  "Nature & Weather": ["nature","weather","自然","天气"],
  "Buildings & Places": ["building","place","建筑","地点"],
  "Actions & Status": ["action","status","control","操作","状态"],
} as const satisfies Record<ToolIconCategory, readonly string[]>;

const LUCIDE_NAME_ALIASES: Readonly<Record<string, string>> = {
  "magic-wand": "wand-sparkles",
  "gallery": "gallery-horizontal"
};

const ICON_KEYWORDS: Readonly<Record<string, readonly string[]>> = {
  database: ["database", "数据库", "数据"],
  "briefcase-business": ["briefcase", "work", "工作", "商务"],
};

function labelFromKey(key: string): string {
  return key
    .split("-")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");
}

export const TOOL_ICONS: readonly ToolIconMetadata[] = ICON_CATEGORIES.flatMap(
  (category) =>
    ICON_KEYS_BY_CATEGORY[category].map((key) => ({
      key,
      label: labelFromKey(key),
      category,
      keywords: [...CATEGORY_KEYWORDS[category], ...(ICON_KEYWORDS[key] ?? [])],
      ...(LUCIDE_NAME_ALIASES[key] ? { lucideName: LUCIDE_NAME_ALIASES[key] } : {}),
    })),
);

export type ToolIconKey = (typeof TOOL_ICONS)[number]["key"];

export const DEFAULT_TOOL_ICON_KEY: ToolIconKey = "app-window";

const iconsByKey = new Map(TOOL_ICONS.map((icon) => [icon.key, icon]));

export function getToolIcon(key: string | null | undefined): ToolIconMetadata {
  return iconsByKey.get(key ?? "") ?? iconsByKey.get(DEFAULT_TOOL_ICON_KEY)!;
}

export function searchToolIcons(
  query: string,
  category: ToolIconCategory | "all",
): ToolIconMetadata[] {
  const normalizedQuery = query.trim().toLocaleLowerCase();

  return TOOL_ICONS.filter((icon) => {
    if (category !== "all" && icon.category !== category) return false;
    if (!normalizedQuery) return true;

    return [icon.key, icon.label, icon.category, ...icon.keywords]
      .join(" ")
      .toLocaleLowerCase()
      .includes(normalizedQuery);
  });
}
