import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

test("All Tools opts into reversible layered glass tiles without changing Quick Access", () => {
  const page = readFileSync(new URL("./page.tsx", import.meta.url), "utf8");
  const styles = readFileSync(new URL("../../styles/secondary.css", import.meta.url), "utf8");

  assert.match(page, /data-all-tools-grid/);
  assert.match(page, /import "@\/styles\/secondary\.css"/);
  assert.match(page, /all-tools-layered-glass/);
  assert.match(page, /all-tools-glass-backplate/);
  assert.match(styles, /\.all-tools-layered-glass \.all-tools-glass-backplate/);
  assert.match(styles, /\.all-tools-layered-glass \.all-tools-glass-face/);
  assert.match(styles, /--tool-glass-backplate-size: 46px/);
  assert.match(styles, /to bottom[\s\S]*color-mix\(in srgb, var\(--tool-glass-border\) 96%/);
  assert.match(styles, /filter: saturate\(1\.72\) brightness\(1\.34\)/);
  assert.doesNotMatch(styles, /0 0 18px color-mix\(in srgb, var\(--tool-glass-border\) 66%, transparent\)/);
  assert.match(styles, /border: 0;/);
  assert.doesNotMatch(styles, /border: 1px solid color-mix\(in srgb, var\(--tool-glass-border\) 78%, rgba\(255, 255, 255, 0\.34\)\)/);
  assert.match(styles, /\.all-tools-layered-glass \.all-tools-glass-face::after/);
  assert.match(styles, /\.all-tools-layered-glass \.all-tools-glass-face::before/);
  assert.match(styles, /repeating-radial-gradient/);
  assert.match(styles, /backdrop-filter: blur\(15px\) saturate\(128%\)/);
  assert.match(styles, /rgba\(255, 255, 255, 0\.075\) 0 0\.52px/);
  assert.match(styles, /opacity: 0\.52;/);
  assert.match(styles, /width: 52px !important;/);
  assert.match(styles, /height: 49px !important;/);
  assert.match(styles, /filter: brightness\(1\.3\) saturate\(1\.22\) contrast\(1\.08\)/);
  assert.match(styles, /\.all-tools-layered-glass \.all-tools-glass-face \{[\s\S]*border: 0 !important;/);
  assert.doesNotMatch(styles, /border-color: color-mix\(in srgb, var\(--tool-glass-border\) 72%/);
  assert.doesNotMatch(styles, /inset 1px 1px 0 rgba\(255, 255, 255/);
  assert.doesNotMatch(styles, /linear-gradient\(150deg, rgba\(255, 255, 255/);
  assert.match(styles, /\.all-tools-layered-glass \.all-tools-glass-face::before \{[\s\S]*padding: 0;[\s\S]*mask: none;/);
  assert.match(styles, /\.all-tools-layered-glass \.all-tools-glass-face:hover::before,[\s\S]*animation: none !important;/);
  assert.match(styles, /box-shadow: 0 9px 18px -14px rgba\(2, 6, 23, 0\.86\) !important;/);
  assert.match(page, /lightVariant=\{index % 6\}/);
  assert.match(page, /all-tools-glass-light-path/);
  assert.match(styles, /\.all-tools-layered-glass\[data-light-variant="0"\]/);
  assert.match(styles, /\.all-tools-layered-glass\[data-light-variant="5"\]/);
  assert.match(styles, /radial-gradient\(ellipse at var\(--tool-light-x\) var\(--tool-light-y\)/);
  assert.match(styles, /--tool-shadow-x: -5px/);
  assert.match(styles, /--tool-shadow-x: 5px/);
  assert.match(styles, /var\(--tool-shadow-x\) var\(--tool-shadow-y\) var\(--tool-shadow-blur\) var\(--tool-shadow-spread\) rgba\(2, 6, 23, var\(--tool-shadow-opacity\)\)/);
  assert.match(page, /all-tools-glass-contact-edge/);
  assert.match(styles, /\.all-tools-layered-glass \.all-tools-glass-contact-edge/);
  assert.match(styles, /linear-gradient\(to top, rgba\(3, 8, 24, 0\.48\), transparent 78%\)/);
  assert.match(styles, /linear-gradient\(to left, rgba\(3, 8, 24, 0\.5\), transparent 80%\)/);
  assert.match(page, /phil-studio:dashboard-entrance-complete/);
  assert.match(page, /data-all-tools-marquee-track/);
  assert.doesNotMatch(page, /data-all-tools-edge-fade/);
  assert.match(page, /timeScale\(0\)/);
  assert.match(page, /timeScale\(1\)/);
  assert.match(page, /aria-hidden="true"/);
  assert.doesNotMatch(styles, /\.all-tools-edge-fade--left/);
  assert.match(styles, /mask-image: linear-gradient\(to right, transparent 0, rgba\(0, 0, 0, 0\.04\) 2%, rgba\(0, 0, 0, 0\.24\) 5%, rgba\(0, 0, 0, 0\.68\) 9%, black 13%, black 87%, rgba\(0, 0, 0, 0\.68\) 91%, rgba\(0, 0, 0, 0\.24\) 95%, rgba\(0, 0, 0, 0\.04\) 98%, transparent 100%\)/);
  assert.match(styles, /filter: blur\(9px\) saturate\(1\.35\)/);
  assert.match(styles, /\.all-tools-layered-glass \.all-tools-glass-face > svg/);
  assert.match(styles, /color-mix\(in srgb, var\(--tool-glass-border\) 46%, rgba\(3, 7, 22, 0\.9\)\)/);
  assert.doesNotMatch(page, /data-quick-access-item[^>]*all-tools-layered-glass/);
});
