import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

const page = readFileSync("src/app/dashboard/page.tsx", "utf8");
const css = readFileSync("src/app/dashboard/dashboard.css", "utf8");
const geometry = readFileSync("src/lib/dashboard/lighthouse-edge.ts", "utf8");
const implementation = `${page}\n${geometry}`;

test("lighthouse edge highlights stay in an independent desktop overlay", () => {
  assert.match(page, /function LighthouseEdgeHighlights/);
  assert.match(page, /createLighthouseEdgeGeometry/);
  assert.match(page, /calculateLighthouseEdgeHit/);
  assert.match(page, /data-lighthouse-edge/);
  assert.match(page, /data-lighthouse-edge="sidebar"/);
  assert.match(page, /lighthouse-edge-overlay/);
  assert.match(page, /createElementNS/);
  assert.match(page, /getTotalLength/);
  assert.match(page, /ResizeObserver/);
  assert.match(page, /visibilitychange/);
  assert.match(page, /document\.visibilityState/);
  assert.match(page, /refreshGeometry/);
  assert.match(page, /highlightCache/);
  assert.match(page, /cachedBeacon/);
  assert.match(page, /cachedBeam/);
  assert.match(page, /cachedSource/);
  assert.match(page, /frameSignature/);
  assert.match(page, /createLighthouseEdgeFrameSignature/);
  assert.doesNotMatch(page, /const source = cachedBeacon\.getBoundingClientRect\(\)/);
  assert.doesNotMatch(page, /const cards = \[\.\.\.root\.querySelectorAll<HTMLElement>/);
  assert.doesNotMatch(page, /const highlights = \[\.\.\.overlay\.querySelectorAll<SVGSVGElement>/);
  assert.doesNotMatch(page, /const beacon = root\?\.querySelector<HTMLElement>/);
  assert.doesNotMatch(page, /const beam = beacon\?\.querySelector<HTMLElement>/);
  assert.doesNotMatch(page, /cards\.forEach\(\(card, index\) => \{\s*const rect = card\.getBoundingClientRect\(\)/);
  assert.match(page, /createElementNS\([^\n]+"radialGradient"\)/);
  assert.match(page, /gradientUnits/);
  assert.match(page, /setAttribute\("cx"/);
  assert.match(page, /setAttribute\("cy"/);
  assert.match(implementation, /Math\.tan/);
  assert.match(implementation, /beamFootprint/);
  assert.match(implementation, /Math\.hypot/);
  assert.match(implementation, /beamAngle - beamHalfAngle/);
  assert.match(implementation, /beamAngle \+ beamHalfAngle/);
  assert.match(page, /const beamHalfAngle = 10/);
  assert.match(implementation, /perimeter \* 0\.42/);
  assert.match(page, /#a5f3fc/);
  assert.match(page, /#a5b4fc/);
  assert.match(page, /#c4b5fd/);
  assert.doesNotMatch(page, /stop-color", "#dcecff"/);
  assert.match(implementation, /perimeterPosition/);
  assert.match(implementation, /leftBoundaryHit/);
  assert.match(implementation, /rightBoundaryHit/);
  assert.doesNotMatch(page, /strokeDasharray = `84/);
  assert.match(page, /lighthouse-edge-path--glow/);
  assert.match(page, /lighthouse-edge-path--halo/);
  assert.match(page, /lighthouse-edge-path--core/);
  assert.match(page, /setAttribute\("opacity"/);
  assert.doesNotMatch(page, /clampedAngle/);
  assert.match(page, /matchMedia\("\(min-width: 1280px\)"\)/);
  assert.match(page, /matchMedia\("\(prefers-reduced-motion: reduce\)"\)/);
  assert.doesNotMatch(page, /data-lighthouse-contact-layer/);
  assert.match(css, /\.lighthouse-edge-overlay/);
  assert.match(css, /\.lighthouse-edge-path/);
  assert.match(css, /\.lighthouse-edge-path--glow/);
  assert.match(css, /\.lighthouse-edge-path--halo/);
  assert.match(css, /\.lighthouse-edge-path--core/);
  assert.match(css, /pointer-events: none/);
  assert.match(css, /@media \(max-width: 1279px\)/);
});

test("the edge overlay does not restack glass-panel children or the marquee", () => {
  assert.doesNotMatch(css, /\[data-lighthouse-edge\]\s*>/);
  assert.equal(/\.all-tools-marquee-track[^}]*z-index/.test(css.replace(/\r?\n/g, " ")), false);
});
